import argparse
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Set, Tuple


def parse_signature(signature: str) -> Tuple[List[str], List[str]]:
    """
    Parses a CoppeliaSim function signature to extract parameters and return types.
    Example: "int handle = sim.getObject(string path)" -> (['int'], ['string path'])
    """
    # Separate return from the function call
    if '=' in signature:
        ret_part, call_part = signature.split('=', 1)
    else:
        ret_part, call_part = '', signature

    # Extract parameters from the call
    match = re.search(r'\((.*)\)', call_part)
    params_str = match.group(1) if match else ''
    params = [p.strip() for p in params_str.split(',')] if params_str else []

    # Extract return types
    returns = [r.strip().split(' ')[0] for r in ret_part.split(',')] if ret_part else []

    return returns, params


def ts_type(c_type: str) -> str:
    """Converts a C/Lua type to a TypeScript type."""
    TYPE_MAP = {
        'string': 'string',
        'char*': 'string',
        'int': 'number',
        'float': 'number',
        'double': 'number',
        'number': 'number',
        'bool': 'boolean',
        'buffer': 'Uint8Array',  # Assuming buffer maps to a byte array in TS
        'table': 'object',  # Generic object for Lua tables
        'map': 'object',  # Generic object for Lua maps
        'void': 'void',
    }
    c_type = c_type.lower()

    # Handle array types
    if '[]' in c_type:
        base_type = c_type.replace('[]', '').strip()
        return f"{TYPE_MAP.get(base_type, 'any')}[]"
    if '*' in c_type and c_type != 'char*':  # Pointer, often implies array or generic
        base_type = c_type.replace('*', '').strip()
        return f"{TYPE_MAP.get(base_type, 'any')}[]"

    return TYPE_MAP.get(c_type, 'any')  # Default to 'any' if no specific mapping


def generate_typescript_definition_file(calltips_path: Path, constants_path: Path, output_d_ts: Path):
    """
    Generates a .d.ts TypeScript definition file from a calltips JSON and a constants JSON.
    """
    print(f"Reading calltips from '{calltips_path}'...")
    with open(calltips_path, 'r', encoding='utf-8') as f:
        calltips = json.load(f)

    print(f"Reading constants from '{constants_path}'...")
    try:
        with open(constants_path, 'r', encoding='utf-8') as f:
            constants_data = json.load(f)
    except FileNotFoundError:
        print(
            f"Warning: Constants file not found at '{constants_path}'. The definition file will be generated without constants.")
        constants_data = {}

    # Group functions by module (sim, simUI, etc.)
    modules: Dict[str, Set[str]] = defaultdict(set)
    for func_name, signature in calltips.items():
        if '.' in func_name:
            module_name = func_name.split('.')[0]
            # Ignore low-level or internal functions
            if module_name in ['string', 'table', 'math', 'os', 'debug', 'coroutine']:
                continue
            modules[module_name].add(func_name)

    print(f"Generating TypeScript definitions for {len(modules)} modules...")

    with open(output_d_ts, 'w', encoding='utf-8') as f:
        f.write("// Type definitions for CoppeliaSim ZMQ Remote API\n")
        f.write("// Project: https://github.com/your-repo/CoppeliaSim-Stubs-Generator\n")
        f.write("// Definitions by: Your Name <https://your.website>\n")
        f.write("// Generated by build_tools/generate_typescript.py\n\n")

        f.write("declare namespace CoppeliaSim {\n")

        for module_name, funcs in sorted(modules.items()):
            f.write(f"    export interface {module_name} {{\n")
            f.write(f'        /** API functions for the `{module_name}` module. */\n\n')

            # Write constants for this module
            if module_name in constants_data:
                f.write("        // --- Constants ---\n")
                sorted_constants = sorted(constants_data[module_name].items())
                for const_name, const_value in sorted_constants:
                    const_type = 'string' if isinstance(const_value, str) else 'number' if isinstance(const_value, (int,
                                                                                                                    float)) else 'any'
                    f.write(f"        readonly {const_name}: {const_type};\n")
                f.write("\n")

            if funcs:
                f.write("        // --- Functions ---\n")

            sorted_funcs = sorted(list(funcs))

            if not sorted_funcs:
                f.write("        // No functions in this module\n")
                f.write("    }\n\n")
                continue

            for func_name in sorted_funcs:
                full_signature = calltips[func_name].split('\n')[0]
                short_func_name = func_name.split('.')[-1]

                try:
                    returns, params = parse_signature(full_signature)

                    # Build the parameter list for TypeScript
                    ts_params = []
                    for i, param in enumerate(params):
                        if not param or param == '...':
                            ts_params.append('...args: any[]')
                            continue

                        parts = param.strip().split(' ')
                        p_type = ts_type(parts[0])
                        p_name = parts[1].split('=')[0].replace('[]', '') if len(parts) > 1 else f'arg{i}'
                        p_name = re.sub(r'[^a-zA-Z0-9_]', '', p_name)

                        optional = '=' in param

                        ts_params.append(f"{p_name}{'?' if optional else ''}: {p_type}")

                    # Build the return type for TypeScript
                    if not returns or 'void' in returns[0] or '' in returns:
                        ts_return_type = 'void'
                    elif len(returns) == 1:
                        ts_return_type = ts_type(returns[0])
                    else:
                        ts_return_type = f"[{', '.join(ts_type(r) for r in returns)}]"

                    f.write(f"        /**\n")
                    f.write(f"         * {full_signature}\n")
                    f.write(f"         */\n")
                    if ":" in short_func_name:
                        f.write(f"        \"{short_func_name}\"({', '.join(ts_params)}): {ts_return_type};\n\n")
                    else:
                        f.write(f"        {short_func_name}({', '.join(ts_params)}): {ts_return_type};\n\n")

                except Exception as e:
                    print(f"Could not process signature for '{func_name}': {full_signature} ({e})")
                    f.write(f"        // Could not generate definition for: {func_name}\n")
                    f.write(f"        // Original signature: {full_signature}\n\n")

            f.write("    }\n\n")

        f.write("    // --- Global API instances ---\n")
        for module_name in sorted(modules.keys()):
            f.write(f"    export const {module_name}: {module_name};\n")

        f.write("}\n")

    print(f"Success! TypeScript definition file saved to '{output_d_ts}'")


def main():
    parser = argparse.ArgumentParser(
        description='Generates a .d.ts TypeScript definition file from CoppeliaSim calltips and constants JSONs.')
    parser.add_argument('calltips_json', type=Path, help='Path to the input calltips.json file.')
    parser.add_argument('constants_json', type=Path, help='Path to the input constants.json file.')
    parser.add_argument('output_d_ts', type=Path, help='Path to the output .d.ts file.')
    args = parser.parse_args()

    generate_typescript_definition_file(args.calltips_json, args.constants_json, args.output_d_ts)


if __name__ == '__main__':
    main()
